import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Navbar from '../Navbar'
import NavbarLink from '../Navbar/navbarLink'
import Footer from '../../components/Footer'

interface LayoutProps {
  content: any,
  title: string
}

const Layout: React.FC<LayoutProps> = ( {content,title}) => {
  const [navbarFixed, setNavbarFixed] = useState<boolean>(false)
  const router = useRouter()
  let navbar = <NavbarLink fixed={navbarFixed}/>

  const handleFixed = () => {
    if (window.scrollY >= 250) {
      setNavbarFixed(true)
    } else {
      setNavbarFixed(false)
    }
  } 

  const handleNavbar = () => {
    if (router.pathname === '/') {
      navbar = <Navbar fixed={navbarFixed} /> 
    }
    return navbar
  }

  useEffect(() => {
    window.addEventListener('scroll', handleFixed)
    return () => {
      window.removeEventListener('scroll', handleFixed)
    }
  }, [])
  return (
    <>
      <Head>
          <title>{ title }</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        { handleNavbar() }
        { content }
        <Footer />
    </>
  )
}

export default Layout